### ISSUE TITLE
UglifyJs throws an error in production mode

### ISSUE THREAD

**Issue by JayT9000** [ptc-iot-sharing/ThingworxDemoWebpackWidget#2]
Hello,
first of all I love to see your solution to directly build Thingworx widgets with modern web techniques. I would like to use this template for some implementations in the future.

I cloned the repository and tried to build your sample with:
```
npm install
npm run init
npm run build
```

Because of the production parameter in webpack.config.js the UglifyJSPlugin will be triggered.
```
if (isProduction) {
        result.optimization = {
            minimizer: [
                new UglifyJSPlugin({
                    uglifyOptions: {
                        beautify: false,
                        compress: true,
                        comments: false,
                        mangle: false,
                        toplevel: false,
                        keep_fnames: true
                    }
                })
            ]
        };
    }
```

This ends in an error:

ERROR in widgetRuntime.bundle.js from UglifyJs
Unexpected token: name «TWPropertyAspect», expected: punc «;» [widgetRuntime.bundle.js:330,6]

ERROR in widgetIde.bundle.js from UglifyJs
Unexpected token: name «TWPropertyAspect», expected: punc «;» [widgetIde.bundle.js:217,6]

Do you have any ideas how to fix this?
npm run watch works fine because Uglify is not used.

**Comment by BogdanMihaiciuc** [comment]
The solution to this is to replace UglifyJs with Terser.

1. Under `package.json`, replace uglify with `terser-webpack-plugin`.
2. Under `webpack.config.js`:

Replace the import on line 5:
```js
const UglifyJSPlugin = require('terser-webpack-plugin');
```

Replace the uglify constructor parameter; the `uglifyOptions` property changes to `terserOptions`:
```js
result.optimization = {
            minimizer: [
                new UglifyJSPlugin({
                    terserOptions: {
                        beautify: false,
                        compress: true,
                        comments: false,
                        mangle: false,
                        toplevel: false,
                        keep_fnames: true
                    }
                })
            ]
        };
```

**Comment by JayT9000** [comment]
Ok, thanks! The Terser minifier works fine. Do you change it also in your repository or shall I change it?

**Comment by BogdanMihaiciuc** [comment]
We'll change it here soon as well.
