### ISSUE TITLE
Update property during runtime

### ISSUE THREAD

**Issue by illyaro** [ptc-iot-sharing/ThingworxDemoWebpackWidget#59]
Hi. I was trying to learn how to create extensions using this template and developed simple Thingworx widget using the code from the other one I've coded in eclipse.
But I could not get how to update properties during runtime. In a classic way it's done this way:
```js
this.updateProperty = function (updatePropertyInfo) {
        if (updatePropertyInfo.TargetProperty === 'myProperty') {
    		this.setProperty('myProperty', updatePropertyInfo.RawSinglePropertyValue);
        }
 };
 ```
 This is the [project ](https://github.com/illyaro/QRCodePrinterWebpack.git)I talk about
 Thank you.

**Comment by stefan-lacatus** [comment]
Take a look at the example here: https://github.com/ptc-iot-sharing/ThingworxDemoWebpackWidget/blob/master/src/runtime/index.ts

It shows the following ways of doing it:
- by adding a setter to your `@property` decorated class field (https://github.com/ptc-iot-sharing/ThingworxDemoWebpackWidget/blob/master/src/runtime/index.ts#L43C48-L45)
- using `@didBind` and `@canBind` decorators: https://github.com/ptc-iot-sharing/ThingworxDemoWebpackWidget/blob/master/src/runtime/index.ts#L54-L64

**Comment by illyaro** [comment]
Thank you I worked
